Trying to show a better 'class' demo ... but not working
I'm stumbling over the 'package' and 'import' and the directory
structure mechanics for Java class and usage.

These compile but the run says:

   Error: Could not find or load main class main
   Caused by: java.lang.ClassNotFoundException: main

It's late ... I'll pick this up tomorrow.

Changes to be committed:
	new file:   build.sh
	new file:   main.java
	new file:   run.sh
	new file:   src/something.java